# Generated by Django 4.1.7 on 2026-05-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('calculation_type', models.CharField(max_length=50)),
                ('inputs_json', models.TextField(default='{}')),
                ('result', models.TextField()),
                ('steps_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
